language: cpp
script: make && make test_suite && make test
install:
  - sudo add-apt-repository -y "deb http://archive.ubuntu.com/ubuntu/ trusty main universe"
  - sudo apt-get update -qq
  - sudo apt-get install gtk-doc-tools libglib2.0-dev autoconf automake
compiler:
  - gcc
