language: cpp
script: make && make test
before_install:
  - sudo add-apt-repository -y "deb http://archive.ubuntu.com/ubuntu/ trusty main universe"
  - sudo apt-get update -qq
  - sudo apt-get install automake autoconf autotools-dev
compiler:
  - gcc
  - clang
